baseURL = "https://blog.dmarcoux.com/"
languageCode = "en"
theme = "hugo-coder"
title = "Dany Marcoux"
paginate = 20
pygmentsStyle = "solarized-light"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
author = "Dany Marcoux"
description = "Blog of Dany Marcoux"
keywords = "blog,web development,developer"
info = "Full Stack Web Developer"
gravatar = "dmarcoux@posteo.de"
dateFormat = "January 2, 2006"
hideFooter = true
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "GitHub"
icon = "fa fa-github"
weight = 1
url = "https://github.com/dmarcoux/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/danymarcoux/"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 3
url = "https://blog.dmarcoux.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
