baseURL = "https://blog.dmarcoux.com/"
languageCode = "en"
theme = "hugo-coder"
title = "Dany Marcoux"
paginate = 20
pygmentsStyle = "borland"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
# Disable taxonomies
disableKinds = ['taxonomy', 'term']

[params]
author = "Dany Marcoux"
description = "Blog of Dany Marcoux"
keywords = "blog,web development,developer"
info = "Full Stack Web Developer"
# Images are under the static directory.
# Hugo will use this image as the website thumbnail whenever sharing a blog post
images = ["images/me.jpg"]
avatarPath = "images/me.jpg"
dateFormat = "January 2, 2006"
# Series see also post count
maxSeeAlsoItems = 5

[[params.social]]
name = "GitHub"
icon = "fa fa-github"
weight = 1
url = "https://github.com/dmarcoux/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/danymarcoux/"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 3
url = "posts/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[menu.main]]
name = "Contact Me"
weight = 2
url = "contact-me/"
