name: Lint

on:
  # Run this workflow when a commit is pushed to `main`
  push:
    branches:
      - main
  # Run this workflow on any PR targeting `main`
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: true # to include themes
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
      - name: Install CLI for markdownlint
        run: npm install markdownlint-cli2 --global
      - name: Lint Markdown files, while excluding anything under the themes and node_modules directories
        run: markdownlint-cli2 "**/*.md" "#themes" "#node_modules"
      # TODO: zola must be installed for this to work
      # - name: Check if the project builds and for broken links
      #   run: zola check
